<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Hanil.TimeGuard.Admin</RootNamespace>
    <AssemblyName>TimeGuard.Admin</AssemblyName>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationManifest>app.manifest</ApplicationManifest>
      <ApplicationIcon>../../assets/timeguard.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../TimeGuard.Core/TimeGuard.Core.csproj" />
  </ItemGroup>
</Project>
